var enchantments = [
{"Namespaced_ID":"aqua_affinity","Name":"親水性\n","Summary":"加快水下挖掘速度\n","MaxLevel":1},
{"Namespaced_ID":"blast_protection","Name":"爆炸保護\n","Summary":"減少爆炸傷害\n","MaxLevel":4},
{"Namespaced_ID":"channeling","Name":"喚雷\n","Summary":"在雨天召喚閃電攻擊生物，僅在雷暴時生效\n","MaxLevel":1},
{"Namespaced_ID":"depth_strider","Name":"深海漫遊\n","Summary":"增加水下行走速度\n","MaxLevel":3},
{"Namespaced_ID":"efficiency","Name":"效率\n","Summary":"加快挖掘速度\n","MaxLevel":5},
{"Namespaced_ID":"feather_falling","Name":"輕盈\n","Summary":"減少跌落傷害\n","MaxLevel":4},
{"Namespaced_ID":"fire_aspect","Name":"燃燒\n","Summary":"使目標著火\n","MaxLevel":2},
{"Namespaced_ID":"fire_protection","Name":"火焰保護\n","Summary":"減少火焰傷害\n","MaxLevel":4},
{"Namespaced_ID":"flame","Name":"火焰\n","Summary":"箭矢使目標著火\n","MaxLevel":1},
{"Namespaced_ID":"silk_touch","Name":"絲綢之觸\n","Summary":"被開採的方塊掉落本身\n","MaxLevel":1},
{"Namespaced_ID":"fortune","Name":"幸運\n","Summary":"增加方塊掉落\n","MaxLevel":3},
{"Namespaced_ID":"impaling","Name":"魚叉\n","Summary":"對水生生物‌‌[僅Java版]或水裡的生物‌‌[僅基岩版]造成額外傷害\n","MaxLevel":5},
{"Namespaced_ID":"infinity","Name":"無限\n","Summary":"射箭不會消耗普通箭矢\n","MaxLevel":1},
{"Namespaced_ID":"knockback","Name":"擊退\n","Summary":"增加擊退距離\n","MaxLevel":2},
{"Namespaced_ID":"looting","Name":"掠奪\n","Summary":"生物能掉落更多物品\n","MaxLevel":3},
{"Namespaced_ID":"loyalty","Name":"忠誠\n","Summary":"使擲出後的三叉戟返回，附魔等級越高，三叉戟返回的用時越短\n","MaxLevel":3},
{"Namespaced_ID":"luck_of_the_sea","Name":"海洋的祝福\n","Summary":"提高釣魚時獲得寶藏的機率\n","MaxLevel":3},
{"Namespaced_ID":"lure","Name":"魚餌\n","Summary":"提高魚咬鉤的速度\n","MaxLevel":3},
{"Namespaced_ID":"multishot","Name":"分裂箭矢\n","Summary":"消耗一支箭可射出三隻箭矢\n","MaxLevel":1},
{"Namespaced_ID":"piercing","Name":"貫穿\n","Summary":"使箭矢穿過多個實體\n","MaxLevel":4},
{"Namespaced_ID":"power","Name":"強力\n","Summary":"增加弓箭傷害\n","MaxLevel":5},
{"Namespaced_ID":"projectile_protection","Name":"投射物保護\n","Summary":"減少來源於彈射物的傷害\n","MaxLevel":4},
{"Namespaced_ID":"protection","Name":"保護\n","Summary":"減少多數的傷害\n","MaxLevel":4},
{"Namespaced_ID":"punch","Name":"衝擊\n","Summary":"增加弓箭的擊退距離\n","MaxLevel":2},
{"Namespaced_ID":"quick_charge","Name":"快速上弦\n","Summary":"減少弩的填裝時間\n","MaxLevel":3},
{"Namespaced_ID":"respiration","Name":"水中呼吸\n","Summary":"延長水中呼吸時間\n","MaxLevel":3},
{"Namespaced_ID":"riptide","Name":"波濤\n","Summary":"將玩家向擲出三叉戟的方向發射，僅在水中或雨中生效\n","MaxLevel":3},
{"Namespaced_ID":"sharpness","Name":"鋒利\n","Summary":"增加近戰攻擊傷害\n","MaxLevel":5},
{"Namespaced_ID":"bane_of_arthropods","Name":"節肢剋星\n","Summary":"對節肢生物造成額外傷害\n","MaxLevel":5},
{"Namespaced_ID":"smite","Name":"不死剋星\n","Summary":"對不死生物造成額外傷害\n","MaxLevel":5},
{"Namespaced_ID":"sweeping","Name":"橫掃之刃 ‌‌[僅Java版]\n","Summary":"增加橫掃攻擊傷害\n","MaxLevel":5},
{"Namespaced_ID":"thorns","Name":"尖刺\n","Summary":"給予攻擊者傷害\n","MaxLevel":3},
{"Namespaced_ID":"unbreaking","Name":"耐久\n","Summary":"減少物品掉耐久的機率\n","MaxLevel":3},
{"Namespaced_ID":"frost_walker","Name":"冰霜行者\n","Summary":"允許水上行走\n","MaxLevel":2},
{"Namespaced_ID":"mending","Name":"修補\n","Summary":"損耗經驗以修補工具的耐久度\n","MaxLevel":1},
{"Namespaced_ID":"binding_curse","Name":"綁定詛咒\n","Summary":"物品無法被丟棄\n","MaxLevel":1},
{"Namespaced_ID":"vanishing_curse","Name":"消失詛咒\n","Summary":"物品會在玩家死亡時消失\n","MaxLevel":1},


];